output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks.cluster_security_group_id
}

output "cluster_node_security_group_id" {
  value       = module.eks.cluster_primary_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks.config_map_aws_auth
}

output "node_groups" {
  description = "Outputs from node groups"
  value       = module.eks.node_groups
}

output "test" {
  value = data.aws_subnet_ids.private
}

output "psql_secret" {
  value = module.aurora.this_rds_cluster_master_password
  sensitive = true
}

output "psql_master_username" {
  value = module.aurora.this_rds_cluster_master_username
}

output "psql_endpoint" { 
  value = module.aurora.this_rds_cluster_endpoint
}
